language: android
android:
  components:
    - build-tools-19.0.3
    - android-8
    - android-14
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

before_install:
  - wget http://dl.bintray.com/sbt/debian/sbt-0.13.2.deb
  - sudo dpkg -i sbt-*.deb

script: sbt test
